# infrastructures/base/authentik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: authentik
      version: "2025.2.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 1m
  install:
    createNamespace: true
  targetNamespace: authentik
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        pullPolicy: IfNotPresent
      env:
        AUTHENTIK_BOOTSTRAP_PASSWORD: "password"
        AUTHENTIK_BOOTSTRAP_TOKEN: "password"
    authentik:
      secret_key: "authentiksecretkey"
      postgresql:
        password: "password"
    redis:
      master:
        persistence:
          size: 1Gi
    postgresql:
      auth:
        username: authentik
        database: authentik
        password: "password"
      primary:
        persistence:
          size: 1Gi
    server:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
        hosts:
          - auth.devkuban.com
        https: false
        pathType: Prefix
