# infrastructures/base/authentik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: authentik
      version: "2025.2.3"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  interval: 1m
  install:
    createNamespace: true
  targetNamespace: authentik
  values:
    authentik:
      secret_key: "cZX7Brt3GwX5mgBV1XPK1Mmr+BzqxIUD6cWlkg8V93oRVliUdmqbl0W1CZZ4aa1jyre13IaFzOBRU7aa"
      error_reporting:
        enabled: true
      postgresql:
        password: "YAvOiXHBadA1s7HKLd1wgxuIcAMNMVI5nFtRHDL1RNGy7YXXwF"

    server:
      ingress:
        enabled: true
        hosts:
          - auth.devkuban.com

    postgresql:
      enabled: true
      auth:
        password: "YAvOiXHBadA1s7HKLd1wgxuIcAMNMVI5nFtRHDL1RNGy7YXXwF"

    redis:
      enabled: true
