# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: ".*templates.*"
        args: [--allow-multiple-documents]
    -   id: check-added-large-files
-   repo: local
    hooks:
      - id: kustomize_build
        name: kustomize build all
        entry: script/ci-verify.sh
        exclude: "^charts.*"
        language: script
