# KyvernoFluxDev/kyvernofluxdev/infrastructures/dev/dev-nbu-dus2/kyverno/kyverno
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  values:
    features:
      validatingAdmissionPolicyReports:
        enabled: false
