#KyvernoFluxDev/kyvernofluxdev/clusters/dev/dev-nbu-dus2
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  path: ./clusters/dev/dev-nbu-dus2
