# KyvernoFluxDev/kyvernofluxdev/infrastructures/dev/devcluster2/flux-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../../base/000-helm-repository
