# infrastructures/base/000-helm-repository/policy-reporter.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.goauthentik.io
