# infrastructures/base/000-helm-repository/policy-reporter.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: policy-reporter-repo
  namespace: flux-system
spec:
  interval: 24h
  url: https://kyverno.github.io/policy-reporter
