#KyvernoFluxDev/kyvernofluxdev/clusters/dev/devcluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructures/local
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
