#KyvernoFluxDev/kyvernofluxdev/clusters/dev/devcluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/2.3.0
  - infrastructures.yaml
patches:
  - path: patch.yaml
