# infrastructures/dev/devcluster2/policy-reporter/patch.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
  namespace: flux-system
spec:
  values:
    ui:
      enabled: true
